name: 'Zeus Build and Preview'
description: 'Build app with Zeus and generate preview QR code'
inputs:
  zeus_login_success:
    description: 'Whether Zeus authentication was successful'
    required: true
outputs:
  preview_url:
    description: 'Zeus preview URL'
    value: ${{ steps.zeus_preview.outputs.PREVIEW_URL }}
  zeus_qr_generated:
    description: 'Whether Zeus QR code was generated'
    value: ${{ steps.zeus_preview.outputs.ZEUS_QR_GENERATED }}

runs:
  using: 'composite'
  steps:
    - name: Build app with Zeus
      shell: bash
      run: zeus build
    
    - name: Generate Zeus Preview QR Code
      id: zeus_preview
      if: inputs.zeus_login_success == 'true'
      shell: bash
      run: |
        # Last modification done in PR iricigor/ZeppNightscout#54
        echo "Last modification to Zeus Preview QR Code generation: PR #54"
        
        # Run the Zeus preview script
        bash scripts/generate-zeus-preview.sh
